### ISSUE TITLE
Add deepl app as floating text selection action in other apps

### ISSUE THREAD

**Issue by fm-sys** [sakusaku3939/DeepLAndroid#1]
First of all: Very cool work!!!

But what about adding your DeepL app as floating text selection action in other apps? That would IMHO be very useful...

It's explained here step-by-step:
https://medium.com/androiddevelopers/custom-text-selection-actions-with-action-process-text-191f792d2999

**Comment by sakusaku3939** [comment]
Thank you for suggesting this new feature.
In fact, it was very easy to create a floating text selection action.

A new version is available here:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v2.0

**Comment by fm-sys** [comment]
Tested it and it's working like a charm... Thank you so much!
