### ISSUE TITLE
DeepL translation popup is not working in the Mastodon app

### ISSUE THREAD

**Issue by d4f5409d** [sakusaku3939/DeepLAndroid#101]
Link to the Mastodon app: https://github.com/mastodon/mastodon-android

Android 13, OnePlus 8, OxygenOS

**Comment by sakusaku3939** [comment]
Hi! Thanks for the information.
I have installed and verified the Mastodon app, and it appears that the context menu items are restricted.
As a workaround, you can start DeepL from the context menu "Share".
