### ISSUE TITLE
It takes a long time to open an application (Two full seconds)

### ISSUE THREAD

**Issue by Wjxfi** [sakusaku3939/DeepLAndroid#103]
I have only two applications that take so long to open. (Among 1,300)
This is not normal. Please speed up the opening time

look at the official deepl app, it opens instantly, take it as an example

**Comment by sakusaku3939** [comment]
Since it is displayed using WebView (imagine a web browser), it is difficult to reduce the initial startup time any further.
Currently I recommend the use of the official application.
I apologize that it has taken me over a year to respond to this reply.

**Comment by sakusaku3939** [comment]
There are two reasons.

- One is that this application, different from huggingchat, is loading JavaScript in the process of hiding. In addition, it also loads jQuery.
- The second is that the process of hiding the element must be done after the DOM has finished rendering. If we remove the logo on initial launch before the type is displayed, the display will not be fully consistent.

I have confirmed that eliminating both of these processes would result in speeds similar to huggingchat. However, promotions will still be displayed.

**Comment by sakusaku3939** [comment]
But for the second one, I feel that showing the display process is at least a better user experience than just the logo, so I will add it to the v8.3 changes.
