### ISSUE TITLE
hide it (request)

### ISSUE THREAD

**Issue by Wjxfi** [sakusaku3939/DeepLAndroid#104]
>JavaScript is used to hide all but the most necessary elements.

it is not true

There's a deepl pro ad and "download for free" ad (hide it)

I am also very concerned about the company reviews below (like everything else I have listed above).

**Comment by raniesantos** [comment]
![Screenshot_20230705-082945](https://github.com/sakusaku3939/DeepLAndroid/assets/8528269/dcf2db3d-ea76-4255-a602-f7781cc772ba)
Needs update to hide promotions.

**Comment by sudoshindo** [comment]
@sakusaku3939 

**PLEASE USE THIS TO UPDATE init.js CODE**

**Comment by sakusaku3939** [comment]
Sorry. And thank you so much for working on the fix!
I haven't used this app for over 2 years now, so I had no motivation to update it. I can make this fix myself, but if you want to keep your name as a contributor, please create a pull request [here](https://github.com/sakusaku3939/DeepLAndroid/pulls).
I will make the release to F-Droid.

P.S.
I believe this fix will solve the problem for a while. However, the DeepL site requires periodic CSS modifications as the design is updated regularly. (So we have made 7~8 major revisions in the past)

**Comment by sakusaku3939** [comment]
I have updated to v8.2 and will be released an update to F-Droid in a few days.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.2

If you see the promotion again, please open a new Issue.
Thank you @sudoshindo.
