### ISSUE TITLE
Hide it please...

### ISSUE THREAD

**Issue by Wjxfi** [sakusaku3939/DeepLAndroid#111]
![nWnWY9jAIR.jpg](https://github.com/sakusaku3939/DeepLAndroid/assets/113500363/f78fca9f-3a67-4cff-a7fb-6588c1e9f1ba)

![a788jdN0gz.jpg](https://github.com/sakusaku3939/DeepLAndroid/assets/113500363/118a4e50-a5b5-469d-92c5-0b229a444011)

**Comment by sakusaku3939** [comment]
@Wjxfi If you click close on each one and restart, the cookies will be saved and will not appear next time.

**Comment by sakusaku3939** [comment]
Hi, I have made an update to hide the Cookies banner in v8.3.
However, the two banners on DeepL appear to be managed by the DeepL server, not the client side Cookies. Therefore, please click the close button yourself to hide this one. (They will not be displayed next time)

v8.3 link:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.3

![image](https://github.com/sakusaku3939/DeepLAndroid/assets/53967490/9dcd050b-f593-47a8-9d76-6ad2e6031d8e)
