### ISSUE TITLE
Cookies button doesn’t work

### ISSUE THREAD

**Issue by xplosionmind** [sakusaku3939/DeepLAndroid#113]
The buttons in popup box asking to accept cookies are not working: if clicked, the popup is not closed.

**Comment by owosoup** [comment]
Yep, same

**Comment by sakusaku3939** [comment]
Hmm, if that's the case, then there might not be a problem with the cookie related code in v8.3...
Is it not possible to close the cookie popup in v8.1 as well?

**Comment by merito** [comment]
I've got the issue on 8.2 and 8.3, downgrading to 8.1 resolves the problem.

**Comment by owosoup** [comment]
To me, 8.1 still has the issue on realme UI.

**Comment by sakusaku3939** [comment]
Thanks for the feedback on the bug.
I have made a test release of the fix as I cannot reproduce it in my environment.
Please let me know the results of updating to v8.4 and uninstalling and installing v8.4.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.4

**Comment by sakusaku3939** [comment]
I will add a note to the release details.
@AnthillSudoku Thank you for your report.👍

**Comment by owosoup** [comment]
Works for realme UI too!

**Comment by xplosionmind** [comment]
It is still not working for me in 8.4, unfortunately…

**Comment by sakusaku3939** [comment]
@xplosionmind Is it still the same if I uninstall and then reinstall?

**Comment by xplosionmind** [comment]
> @xplosionmind Is it still the same if I uninstall and then reinstall?

Aaaaah, you’re right! I forgot to do it. After deleting all app data, uninstalling, and then reinstalling, the cookies buttons work normally!

Thanks a lot!

**Comment by sakusaku3939** [comment]
OK! I'm glad it was resolved.

**Comment by sakusaku3939** [comment]
This time I can reproduce it in my environment and will try to fix it when I have time.
@AnthillSudoku Thanks for reporting it.
