### ISSUE TITLE
Cookie notice won't disappear

### ISSUE THREAD

**Issue by HarriBuh** [sakusaku3939/DeepLAndroid#116]
![Screenshot_20240801-185534.png](https://github.com/user-attachments/assets/60dcdc05-f082-4fcb-a20e-3915bc3797d1)

While the notice always appeared from time to time in the past, one has always been able to quickly dismiss it again.
But since an unknown time (days-weeks), the choice won't get saved any more, as it seems. Which will make the notice permanent and it will block almost half of the popup, rendering it useless. 

App version 8.4
Google Pixel 7
Android 14

**Comment by pistolius** [comment]
Same for me.

Google Pixel 6 Pro
 Android 14 AP2A.240605.024
App Version 8.4

**Comment by sakusaku3939** [comment]
Thank you for reporting the bug.
I am already aware of it and it is being fixed. Please wait a moment. ☕

**Comment by sakusaku3939** [comment]
v8.5 has been released and fixed!
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.5

The cause of this issue was an inconsistency with cookies stored on the device when cookies expired.
If the update did not solve the problem, please let me know.

**Comment by pistolius** [comment]
Amazing. Looks good to me :)
