### ISSUE TITLE
Can not switch to Wrtie

### ISSUE THREAD

**Issue by monkeyotg** [sakusaku3939/DeepLAndroid#120]
"Write" is not clickable.
Pixel 7 & Pixel 8 Android 14

![markup_1000032297](https://github.com/user-attachments/assets/8a824f79-0637-4e3f-b428-80c420c0c9c4)

**Comment by monkeyotg** [comment]
> To prevent unpredictable behavior and crashes, the behavior of jumping to links is disabled. This app currently supports Translator only.

Got

**Comment by BabyOilJohnson** [comment]
One request -  could you add an option to change the initial screen to Write.

I can open an issue if needed.

**Comment by sakusaku3939** [comment]
It would be helpful if you could start a new Issue. 👍
