### ISSUE TITLE
Writing assistant popup

### ISSUE THREAD

**Issue by M0lyk** [sakusaku3939/DeepLAndroid#127]
For several days the application has been unusable, a full screen popup about a writing assistance feature takes up the entire page and deprives us of the translation text fields.

FDroid version 8.6

Thank you

![Screenshot_20241205-055706_DeepL.png](https://github.com/user-attachments/assets/14db1591-bc3a-4008-8885-d54af77bc8b0)

**Comment by daitj** [comment]
Same issue here, I cannot click that "Start writing" either. Are all sorts of events blocked in the app, apart from few whitelisted ones?

**Comment by sakusaku3939** [comment]
Hi! Thank you for reporting the bug.
I could not reproduce the popup in my environment. However, the click was disabled by JavaScript, so I changed the logic and fixed it in v8.7.
If you have not fixed it, please reopen the issue. :+1: 
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.7
