### ISSUE TITLE
Feature request - intent receiver for text/plain

### ISSUE THREAD

**Issue by atomizer** [sakusaku3939/DeepLAndroid#14]
Some apps don't show custom items from external apps in the text selection menu. For example, Twidere works like that for some reason. Would be nice to be able to "share" directly to the DeepL app instead of going through clipboard and switching apps manually. Also, maybe there are apps that don't allow text selection but do use the share mechanism.

**Comment by sakusaku3939** [comment]
Thank you for your patience!
I've decided it's a feature I need, since it doesn't show up in the text selection menu in apps like Gmail.

A new version is available here:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v4.0
