### ISSUE TITLE
Freature request: please add translation of Word and PowerPoint files.

### ISSUE THREAD

**Issue by ioctl-user** [sakusaku3939/DeepLAndroid#15]
subj

The server itself can do this.

**Comment by sakusaku3939** [comment]
Hi, I've released a new version that includes these features!

A new version is available here:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v4.0

**Comment by ioctl-user** [comment]
I cannot test it on my phone, because of little screen limitation in app, but nevertheless thanks!
