### ISSUE TITLE
Show alternate translations

### ISSUE THREAD

**Issue by adarsh1001** [sakusaku3939/DeepLAndroid#18]
The web version of DeepL lists alternative translations as well. Would it be possible to integrate this in the app?

![Screenshot_20210619_013821.png](https://user-images.githubusercontent.com/8820038/122611794-8aae7a80-d09f-11eb-9a69-e32cbd0b47aa.png)

**Comment by sakusaku3939** [comment]
In my environment (Pixel C API 27 emulator), these seem to work fine.
If they look different from what's shown in this picture, I'd like you to send me a screenshot of the app version!
Please let me know if my interpretation is wrong.

![screenshot](https://user-images.githubusercontent.com/53967490/123511792-5863d500-d6be-11eb-9800-4b863c7a6f3d.png)

**Comment by adarsh1001** [comment]
When opening the app in full-screen in landscape on a computer (via Anbox or emulator), the alternative translations are shown. But in mobile, it doesn't show up.

![Screenshot_20210626-204032.png](https://user-images.githubusercontent.com/8820038/123517570-5bab9080-d6bf-11eb-9a41-4ac258990dc9.png)

![Screenshot_20210626-204100.png](https://user-images.githubusercontent.com/8820038/123517577-61a17180-d6bf-11eb-8563-cb7c8ee38600.png)

**Comment by sakusaku3939** [comment]
This is because the server side hides the alternate translation when it goes mobile.
This app just uses WebView to display it, so it seems difficult to customize it that way...

![screenshot](https://user-images.githubusercontent.com/53967490/123534247-bfcd6380-d756-11eb-9fef-b5169c0b7f82.png)
