### ISSUE TITLE
Cannot be called for translation

### ISSUE THREAD

**Issue by billng** [sakusaku3939/DeepLAndroid#20]
This is a good app, but recently it cannot be called for translation. Neither can I open the app directly. Maybe there is a limitation set by DeepL. Please update the app, thank you very much!

**Comment by sakusaku3939** [comment]
Thanks for your report!
Is this a problem related to #19?
Or if it is a different issue, please attach a screenshot 👌

**Comment by billng** [comment]
Hi, sorry I didn't search for closed issues first. This is indeed the same issue and it is now solved, thank you so much!

I would like to suggest that this app will automatically receive update alerts.

Also, I would like to suggest a new feature. Please refer to the following URL, can you translate a web page (with multiple paragraphs) via App/Chrome Extension/Userscript/Bookmarklet and insert the translated content under each paragraph (i.e. bilingual display).

https://fanyi.caiyunapp.com/#/web

I know that the free DeepL has a limit of 5000 characters. Is it possible to translate the contents below 5000 characters one after another and store them temporarily (in the cloud or locally) first? Finally, what about showing all the translated contents together? Is it possible to break the 5,000 character limit this way?

Please refer to the attached image, which is a bilingual translation display. It would be great if DeepL could do this!

![Screenshot_20210704_102205_com kiwibrowser browser](https://user-images.githubusercontent.com/9856151/124371542-47662580-dcb5-11eb-92fc-b35b1dceb006.jpg)

**Comment by sakusaku3939** [comment]
Thanks for the feature request!
However, both of these features are difficult to complete only in the app, and unfortunately I cannot accept your suggestion.

If you still have any other questions, please open the Issue again.
