### ISSUE TITLE
The text copy does not work

### ISSUE THREAD

**Issue by KoumiCZ** [sakusaku3939/DeepLAndroid#23]
Hello, the text copy function does not work in the app if I use the translation function from a third app, see the first screenshot. When I click on the copy text button, see the second screenshot, the translated text is not copied. The clipboard remains empty.

![Screenshot_20210704-224018_Edge](https://user-images.githubusercontent.com/47278294/124398973-dbb5a400-dd18-11eb-8fd4-73c744f07fa8.jpg)

![Screenshot_20210704-223412_DeepL](https://user-images.githubusercontent.com/47278294/124398829-166b0c80-dd18-11eb-9358-70b0a046414d.jpg)

**Comment by sakusaku3939** [comment]
After a lot of testing, I found that the click event is not being called on the JavaScript until some additional text is entered when it is launched from the URL parameter. (Click events on other elements are detectable.)
My guess is that the copy button is not enabled between the time it is launched and when the text is typed. 💭

However, if you use a browser and navigate to the site with the URL parameter included, the copy button works, so I think it is theoretically possible.
I still need to verify the code on the DeepL server a bit more, so it may take some time to resolve this...

**Comment by fm-sys** [comment]
I'm also affected by this bug. For me it does never work, even when I type the text manually.

**Comment by sakusaku3939** [comment]
Good news!
After changing the code to reconfigure the click listener every time a copy button is generated, this bug no longer occurs.

This change will be incorporated into v7.1 in the near future. :tada:

**Comment by sakusaku3939** [comment]
v7.1 has been released!
If you are using F-Droid, it may take a few days for the update to arrive.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v7.1

If it occurs again, please reopen this issue.
