### ISSUE TITLE
Deepl server

### ISSUE THREAD

**Issue by suzukar** [sakusaku3939/DeepLAndroid#3]
Something wrong ?
![SmartSelect_20210311-092533_DeepL](https://user-images.githubusercontent.com/68049741/110721909-0498b300-81d7-11eb-9905-d9f7c7439d90.jpg)

**Comment by fm-sys** [comment]
For me everything works fine. Do you have checked your internet connection?

**Comment by suzukar** [comment]
> For me everything works fine. Do you have checked your internet connection?

Turns out it's an OpenDNS problem.
