### ISSUE TITLE
floating error about dark theme

### ISSUE THREAD

**Issue by lascapi** [sakusaku3939/DeepLAndroid#34]
I got an error message floating everytime above the app.

![Screenshot_20210824-135613](https://user-images.githubusercontent.com/6562527/130612622-e342affa-4e9b-475f-8e9d-cb04da1210f5.png)

App version : 4.3 from f-droid
Android version : 7.1.2

Thank's for this app :)

**Comment by sakusaku3939** [comment]
Do you get this error message even if you don't start in dark mode?

**Comment by S-H-Y-A** [comment]
I think you need to update WebView and Chrome.
Try to Update WebView and Chrome.

[WebView google Play link](https://play.google.com/store/apps/details?id=com.google.android.webview)
[Chrome google Play link](https://play.google.com/store/apps/details?id=com.android.chrome)

**Comment by lascapi** [comment]
I cannot start in dark mode because it's only since Android 10 ( https://developer.android.com/guide/topics/ui/look-and-feel/darktheme )

And everything is up to date. I use LineageOs 14.1 on a Nexus5

**Comment by sakusaku3939** [comment]
Okay, thanks for the information.
I think the error message is probably a mistake in my code.
I'll fix it so that it only shows up when I run it in dark mode.👍

**Comment by sakusaku3939** [comment]
@lascapi 
I tried it on a Nexus 5 with Android version 7.1.1 on an emulator, but could not reproduce it.
In order to narrow down the cause of the problem, I would like you to check if the same phenomenon occurs in the previous version, v4.2.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v4.2

If you get the same error, it is likely that the default theme of LineageOs14.1 is set to dark mode.

**Comment by lascapi** [comment]
Hello, I tried with the 4.2 version and I got zero errors. 

And I'm pretty sure LineageOs14 did't have the dark mode yet.

**Comment by sakusaku3939** [comment]
Hmmm... Then could you please check again with v5.0, which was released 5 days ago?
I'd like to find out if the error still shows up by pressing "dark mode" and "light mode" from the app shortcut that appears by holding down the app icon.

If you want to go further and solve the problem, we can create a dedicated apk for debugging to check the device specifications.
