### ISSUE TITLE
Language switch button isn't colored correctly with darkTheme.

### ISSUE THREAD

**Issue by S-H-Y-A** [sakusaku3939/DeepLAndroid#38]
Language switch button isn't colored correctly with darkTheme.

![Screenshot_20210830-141012337.jpg](https://user-images.githubusercontent.com/74596628/131288339-c1170971-f2e6-48ff-aa84-b6a1cdb5021e.jpg)

**Comment by fm-sys** [comment]
Same applies for the copy button BTW

![Screenshot_20210905_095323_com example deeplviewer](https://user-images.githubusercontent.com/64581222/132119684-30301d0d-ea77-4dda-a342-90c4863120e8.png)

**Comment by Ilithy** [comment]
On my two phones (under Android 11 and 12) these two buttons have the right color:

![_20220118_231849](https://user-images.githubusercontent.com/36798218/150027778-b55b8516-f709-4cee-884f-c3e0a88aa5c6.JPG)

**Comment by sakusaku3939** [comment]
Me too.
Instead, the color of the logo on DeepL has gone wrong.

I don't usually use dark mode, so I don't know, but does anyone know when it changed?
![Screenshot_20220119-170133](https://user-images.githubusercontent.com/53967490/150091904-be6d37b2-cc2d-4217-98bd-a112d156eded.png)

**Comment by Ilithy** [comment]
@sakusaku3939 : Yes indeed, the logo of Deepl is not displayed with a correct color.
I'm not a coder, but if the logo is dark, for it to be displayed correctly, you should set ... `forceDarkAllowed` to `false` for this element? (I may say something stupid, in this case I apologize)

**Comment by Donkey-Doug** [comment]
Android 10
Lineageos

I also have wrong colors (same as first screenshot)
