### ISSUE TITLE
Save translate direction

### ISSUE THREAD

**Issue by yuchdev** [sakusaku3939/DeepLAndroid#4]
Currently, every application start, translate direction falls back on the default, German. Would be nice to have it saved from the last time.

**Comment by sakusaku3939** [comment]
Thanks for the good idea!
I have finished implementing this feature, please check the new version.

https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v3.1

**Comment by yuchdev** [comment]
Thank you for a quick response, and for the useful application.
