### ISSUE TITLE
Force new language selector design 

### ISSUE THREAD

**Issue by fm-sys** [sakusaku3939/DeepLAndroid#41]
Before the latest release, the language selector appeared in a modern mobile optimized bottom sheet dialog. This style is still used when accessing deepl via a web browser. 

![Screenshot_20210905_094805_org mozilla firefox](https://user-images.githubusercontent.com/64581222/132119875-d9ced793-e0aa-4c0d-8fe2-569fe09ca53d.jpg)

However, inside the app a normal single selection pop-up dialog is shown again since last release. Maybe caused by the introduction of the "switch" button? 

![Screenshot_20210905_094815_com example deeplviewer](https://user-images.githubusercontent.com/64581222/132119931-861a561c-50ed-4db1-aa7f-6882dac2fa0d.jpg)

**Comment by sakusaku3939** [comment]
The exact opposite seems to be happening in this environment.
Maybe the DeepL server is doing A/B testing.

![screen-20210906-152520_2](https://user-images.githubusercontent.com/53967490/132170772-d5cedc9d-ac3e-4413-90ce-a74a551d2fd6.gif)

**Comment by fm-sys** [comment]
Ok. Probably we have to wait until the feature is rolled out to everybody. Or maybe there's a way to force the new language selector?

**Comment by fm-sys** [comment]
After clearing the app-cache, the new language selector did appear again. So let's close the issue, no action required...
