### ISSUE TITLE
No button present to swap languages

### ISSUE THREAD

**Issue by kokroo** [sakusaku3939/DeepLAndroid#52]
In the desktop view, there's a button to instantly swap the input and output languages. Could we possibly add it to this?

**Comment by sakusaku3939** [comment]
Hi.
In my environment, that button is displayed.
Can you please tell me the device name and version?

![Screenshot_20211122-191559_1](https://user-images.githubusercontent.com/53967490/142845131-8d01c359-d12b-4596-b805-fd56b1c23e76.png)
