### ISSUE TITLE
Add background to settings icon 

### ISSUE THREAD

**Issue by fm-sys** [sakusaku3939/DeepLAndroid#55]
On my device, the settings icon is totally invisible. This could be solved by adding background to settings icon... 

![Screenshot_20211210_154750_com huawei android launcher](https://user-images.githubusercontent.com/64581222/147392562-de8c4b63-c97c-4f49-ba26-7ed2a450fb74.png)

**Comment by sakusaku3939** [comment]
Okay. I will deal with it in the near future. :eyes:

**Comment by sakusaku3939** [comment]
This fix has been incorporated into v6.4!
Please check if it works correctly:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v6.4

**Comment by fm-sys** [comment]
First of all, thanks for working on it!

However, I don't see a change with the new release. Looking at the code, you've replaced the SVG with a bitmap image, which however has a transparent background as well...

**Comment by sakusaku3939** [comment]
Hmmm....
Just in case, it is possible that the cache is still there. Do you get the same result after reinstalling?

**Comment by fm-sys** [comment]
> Do you get the same result after reinstalling?

Yes.

The PNG is transparent:

![Screenshot_20211230_100636_org mozilla firefox_copy_410x354](https://user-images.githubusercontent.com/64581222/147737670-ca4ca672-d152-4b97-807f-254a4847ad70.png)

**Comment by sakusaku3939** [comment]
Oh, I'm sorry for my lousy work.🙄
Thanks for finding it! I'll fix it right away.

**Comment by fm-sys** [comment]
Don't worry, such things can happen to everyone... Thanks for working on it!

**Comment by sakusaku3939** [comment]
Version v6.4 has been updated. Please check it out.

**Comment by fm-sys** [comment]
Works! Thanks for fixing it... 👍
