### ISSUE TITLE
[Feature request] Traditional Chinese Please...

### ISSUE THREAD

**Issue by AstaFatherSatan666** [sakusaku3939/DeepLAndroid#58]
Simplified shouldn't be the only option. It's vastly different in a lot of ways... There's a few countries as well who use traditional based systems. 謝謝（thanks Very much。）

**Comment by fm-sys** [comment]
This is a limitation of deepl.com, nothing we can do here...

You can rather target the request to deepl directly:
https://support.deepl.com/hc/en-us/requests/new

**Comment by AstaFatherSatan666** [comment]
Alright
