### ISSUE TITLE
Can't scroll through languages when launched in pop-up mode.

### ISSUE THREAD

**Issue by sakusaku3939** [sakusaku3939/DeepLAndroid#59]
*From F-droid's support email.*

![Screenshot_1641353761](https://user-images.githubusercontent.com/53967490/148157284-0e5e8ca5-6501-468e-828e-e212862ae2a5.png)

**Comment by i1Last** [comment]
Seconded by. The same problem, and my language is very low on this list (Russian)

**Comment by fm-sys** [comment]
Indeed I can reproduce. Although I thought it was working in the emulator while implementing this feature...?!

**Comment by sakusaku3939** [comment]
I changed the specification a bit, because scrolling up the language list overlaps with the action of closing the popup.:eyes:

From the next version, the popup will close only when you tap on a dark area.

**Comment by fm-sys** [comment]
> From the next version, the popup will close only when you tap on a dark area.

Need to test it on a real device first, but is that really an acceptable solution?

**Comment by fm-sys** [comment]
Commit fe7fcc4  was ok as quick-fix, but it had introduced another glitch:

The popup should only collapse as soon as the webview has reached the upper scroll end. (Then we don't need the "will close only when you tap on a dark area"-workaround anymore as well)

![Video](https://user-images.githubusercontent.com/64581222/148662728-fdab25f9-edf3-4d9a-8f87-bfd88b1e95a9.gif)
