### ISSUE TITLE
Line feeds are removed when using floating text selection action.

### ISSUE THREAD

**Issue by sckemu** [sakusaku3939/DeepLAndroid#6]
When using the floating text selection action to select text with line feeds, the line feeds will be removed and translated.

**Comment by fm-sys** [comment]
I think we should escape all special characters (`/?%#\n` and maybe more).

https://stackoverflow.com/questions/58504422/how-to-handle-special-characters-in-api-url-retrofit

**Comment by sakusaku3939** [comment]
Thanks for the helpful information.
I have solved the problem related to #5.

A new version is available here:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v3.2

**Comment by sckemu** [comment]
Thank you! Works great!
