### ISSUE TITLE
#5 #24 has recurred.

### ISSUE THREAD

**Issue by S-H-Y-A** [sakusaku3939/DeepLAndroid#60]
#5 ,#24 occurs when app is opened from floating context and I click switch language button.

Video
<table>
<tr>
	<td>

https://user-images.githubusercontent.com/74596628/148212481-7750a4a2-2096-4e94-b065-70b0d6d1c314.mp4
</td>
	<td>

https://user-images.githubusercontent.com/74596628/148212474-05f6b1ba-199d-42ea-afa9-f44be91ba3c1.mp4
</td>
</table>

**Comment by S-H-Y-A** [comment]
DeepL Version v7.0
Android OS 11, CherishOS2.9 ZenFoneMaxPro(M2)

**Comment by S-H-Y-A** [comment]
I think there is a problem with the implementation of `patch-switchLanguage.js`.

**Comment by sakusaku3939** [comment]
I found out that there was a problem with the implementation of the language switch button, regardless of whether it was activated from the context menu or not.
The problem was solved by adding escaping to `patch-switchLanguage.js`.

Thank you for reporting the bug.:+1:

**Comment by sakusaku3939** [comment]
It's been incorporated into v7.1. 🎉
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v7.1
