### ISSUE TITLE
Pop-up animation very choppy

### ISSUE THREAD

**Issue by silviuk** [sakusaku3939/DeepLAndroid#62]
When it pops up, it has 3-5 fps on my S21 Ultra Exynos, Android 12.

**Comment by sakusaku3939** [comment]
Thank you for your information.
If it's all right, I'd appreciate it if you could send me a video as well.

**Comment by fm-sys** [comment]
Maybe it's caused by the webview? What about waiting until the website is loaded, before we actually open the popup?

**Comment by silviuk** [comment]
> 

Here is a sample recording:
https://file.io/kTuDZz96920M

Thank you for looking into it!

**Comment by fm-sys** [comment]
"_The file you requested has been deleted_"

I'm unable to download the file. Can you upload it directly into this github issue?

**Comment by silviuk** [comment]
https://user-images.githubusercontent.com/2750371/148637011-de0d2a06-b196-4032-ad5e-35b635ae843f.mp4

**Comment by fm-sys** [comment]
Thanks! This confirms my assumption that we should wait for the website to load before showing the popup... However, some other loading identicator should be shown in the meantime.

**Comment by fm-sys** [comment]
I would volunteer to help here... (as time permits)

@sakusaku3939 can you assign me?

**Comment by sakusaku3939** [comment]
Sorry for the delay in confirmation.
I've assigned @fm-sys.
