### ISSUE TITLE
Please adjust versionCode and versionName

### ISSUE THREAD

**Issue by IzzySoft** [sakusaku3939/DeepLAndroid#7]
All releases up to the current v3.1 seem to identify as

    package: name='com.example.deeplviewer' versionCode='1' versionName='1.0'

which is not only confusing, but also has some other disadvantages:

* it makes updates hard. As Android uses `versionCode` to tell versions apart, it would not offer updating to e.g. v3.1 from an installed v3.0 as it sees the two as identical versions
* it makes error reporting in issues hard to pin as the user would have a hard time seeing which version is installed

For `versionName` (which is what the end-user sees) it's easy: just keep it in sync with the release/tag name. As for `versionCode`, the simplest approach is to use it as "release counter", always just incrementing it by 1 (never ever decrement :wink:)

Thanks for considering!

**Comment by sakusaku3939** [comment]
Oh, I'm sorry! That was due to my lack of study...
I've now updated versionCode and versionName for v3.1 only, should I fix this for past versions as well?

**Comment by IzzySoft** [comment]
No, I don't think that's necessary. For the latest version should suffice for now – and of course for future ones. Will you replace the APK at the release as well? If so, that update would be fetched with the next sync tomorrow.

Oops, context: your app became [available here](https://apt.izzysoft.de/fdroid/index/apk/com.example.deeplviewer) just now. Updates will be fetched automatically within 24h of your attaching the APK to a new release. If you want to, you can use [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there so users become aware they can use the [F-Droid](https://f-droid.org/) client to install your app and be automatically notified about updates.

Two more things I can offer you:

1. a PR to establish [Fastlane structures](https://gitlab.com/snippets/1895688)
2. getting your app to the F-Droid repo itself (which would require those Fastlane structures)

Just let me know if you're interested :smile:

**Comment by sakusaku3939** [comment]
Thank you for your suggestion. I would like to accept your offer.
In the meantime, I would like to release a version that includes these changes first.
If there is anything else I should do, please let me know.

**Comment by IzzySoft** [comment]
> I would like to accept your offer.

Find the PR linked then. It's the very basic starter package. Be welcome using my Fastlane Cheat Sheet (linked above) to build on it – eg. moving the screenshots inside. Would be good to have this merged before you tag the next release. Just let me know when you feel ready to start with F-Droid, so we can initiate that.

**Comment by sakusaku3939** [comment]
Okay, I've completed the Fastlane setup. Please let me know if there is anything I am missing.
Thank you for your help.

**Comment by IzzySoft** [comment]
Thanks, looks good (including Japanese) :green_heart: You might wish to add screenshots (e.g. to `fastlane/metadata/android/en-US/images/phoneScreenshots/` – as `en-US` is the fallback for all things, no need to duplicate them to other languages unless they are "localized" and thus no duplicates).

I've just triggered a manual update: new Fastlane descriptions (for JP) where picked up fine together with a new v3.2, `versionCode`/`versionName` fit nicely. Looks like you're ready for opening an [RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging) with F-Droid. Let me know if you need help with that (disclosure: I'm one of the F-Droid maintainers).

Btw: feel free to close this issue (the initial problem is solved by now) and, if needed, ping me from a dedicated F-Droid issue. Of course we can also complete that here if you prefer.

**Comment by sakusaku3939** [comment]
Thank you so much!
