### ISSUE TITLE
Add DeepL to QS

### ISSUE THREAD

**Issue by i1last** [sakusaku3939/DeepLAndroid#72]
**I would like to suggest adding DeepL to the QS**, as not all applications can call DeepL through the popup menus of text editing: (in this case in the screenshot of Nekogram)
![Screenshot_20220121-185109_Nekogram](https://user-images.githubusercontent.com/90155905/150557643-80cbe538-34a9-4282-8ae9-0c511a0e4b05.png)

At Yandex Translate you can display a button in QS and it is very convenient!

![Screenshot_20220121-185331_Chrome](https://user-images.githubusercontent.com/90155905/150558086-ef7ce7f1-c4da-47b2-aff1-d58b0f8176ec.png)
![Screenshot_20220121-185417_Translate](https://user-images.githubusercontent.com/90155905/150558111-869b828a-dbad-40a2-8a35-75f57dac545a.png)

**Comment by sakusaku3939** [comment]
Thanks for the feature request! And sorry for the delay in implementation.
It is simple, but incorporated in v8.0.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.0

If you have any questions or requests, please open a new issues.:+1:
