### ISSUE TITLE
It switches to the full mobile page

### ISSUE THREAD

**Issue by CodeCubeNeo** [sakusaku3939/DeepLAndroid#78]
Hello. With the update the app shows the full mobile web page, asks for cookies, the web footer, it advertises the pro version and there is a mising button for switching the languages (two arrows pointing in different directions). It is weird, the first time I launch it it loads normal (just two textboxes with lamguage selection and a switch button, like the old one before the update), but when I open it the second time the whole page loads.

**Comment by sakusaku3939** [comment]
Hi! This issue is currently being fixed.
Please see this issues (#77) for more information.
