### ISSUE TITLE
material you

### ISSUE THREAD

**Issue by andsofine** [sakusaku3939/DeepLAndroid#83]
like google translate

**Comment by sakusaku3939** [comment]
The application wraps the translation screen of the DeepL official website, so it is difficult to change the design...

**Comment by sakusaku3939** [comment]
@andsofine
It is possible to create your own application by using the DeepL API. But I do not plan to implement it in this application in the future.
Please see [this comment](https://github.com/sakusaku3939/DeepLAndroid/issues/81#issuecomment-1114367788) for a detailed explanation.

**Comment by sakusaku3939** [comment]
> no, I meant without API. somehow impose your design over

It is implementationally difficult to replace it with your own design while running WebView in the background.

**Comment by sakusaku3939** [comment]
Those changes would be disruptive to the users who have been using the system, so we would have to create a new project.
Therefore, DeepLAndroid does not plan to adopt them.:cry:
