### ISSUE TITLE
copy translation not working

### ISSUE THREAD

**Issue by andsofine** [sakusaku3939/DeepLAndroid#90]
"translation copied" but it is not

**Comment by toas-koas** [comment]
I have the same issue

Pixel 2XL Android 12 DivestOS
DeepL Version 7.6

**Comment by pistolius** [comment]
I have the same issue. I can copy just fine by highlighting, though. 

Pixel 6 Pro. Android 13. DeepL 7.6.

**Comment by sakusaku3939** [comment]
Hi! Thanks for reporting the issue.
This issue has been fixed in v8.0.
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v8.0

**Comment by pistolius** [comment]
This has broken again?
