### ISSUE TITLE
Make Deepl Pro ad less intrusive

### ISSUE THREAD

**Issue by Donkey-Doug** [sakusaku3939/DeepLAndroid#92]
The Deepl pro ad is currently kinda intrusive. I support the ad, but maybe make it less annoying.

**Comment by KazKaz90** [comment]
Simply use the official DeepL Translator app instead.

**Comment by KazKaz90** [comment]
Why the dislikes? Lmao

**Comment by sakusaku3939** [comment]
@KazKaz90 This is only an unofficial app, so I do not have the authority to improve the DeepL site.
I find the Pro ads disturbing, so this app with a hackish way to remove them.
