### ISSUE TITLE
New(?) elements to remove

### ISSUE THREAD

**Issue by Mokura** [sakusaku3939/DeepLAndroid#96]
There might be more (I have a filter that zaps cookie notices, for-ex) but the following are ublock origin filters I use to simplify DeepL on Firefox Mobile.

`
deepl.com##.TranslatorPage-module--otherSections--Ko\+6x
deepl.com##footer
deepl.com##.AppBanner-module--banner--2Ezkw
deepl.com##a[href^="/pro"]
`

Which results in this:
![Screenshot_20220906-095501_Fennec](https://user-images.githubusercontent.com/5167919/188654624-044185cb-711c-49d4-998c-b4bd03350b9b.png)

I might have to go back and get a different selector for the last element - I'm not as knowledgeable about scrubbing things with JS/CSS vs ublock filters.

**Comment by sakusaku3939** [comment]
Thanks to this, I noticed that every time the design of the DeepL site changes, the hash value of the class name changes.
`.TranslatorPage-module--otherSections--3cbQ7 -> .TranslatorPage-module--otherSections--Ko+6x`

A corrected version will be released soon.:+1:

**Comment by Mokura** [comment]
It's a somewhat common tactic used by bigger companies' sites in order to combat content filtering (like adblocking lists).  It's very gross, and I can't imagine it does any favors for code readability, either.  Thank you for your work!
